### ISSUE TITLE
今天连接的时候发现服务器端进程没有了

### ISSUE THREAD

**Issue by setsunawang** [UnsignedInt8/LightSword#8]
昨天仅仅试用短暂连接了两次，今天连不上才发现的。
看了下服务器(ubuntu14.04)内存很充裕啊，256M才用了50M多，其他进程都好好的。
这个进程为什么会自动关闭呢

**Comment by setsunawang** [comment]
uptime看了下好像是昨天vps被供应商重启了，已close

**Comment by UnsignedInt8** [comment]
:)
